### ISSUE TITLE
Can we support asio transport with Asio, rather than Boost.Asio? 

### ISSUE THREAD

**Issue by unphased** [zaphoyd/websocketpp#324]
As far as I can tell, [Asio](http://think-async.com/Asio/AsioAndBoostAsio) is actually the "real" Asio, Boost.Asio is simply the version of it packaged with Boost which has a non-header-only dependency (Boost.System). 

Since we all like the cleanliness of header-only, I was wondering about how feasible it was to use Asio with websocketpp, so that we can get actual async transport for websocketpp while maintaining header-onliness.

**Comment by zaphoyd** [comment]
This issue has been addressed on the develop branch and will be included in 0.6.0. define `ASIO_STANDALONE` before any WebSocket++ header to use standalone asio rather than boost::asio. A full C++11 compiler is required to use standalone Asio.

**Comment by zaphoyd** [comment]
Support for standalone Asio has been released in 0.6.0.

**Comment by ArosPrince** [comment]
I tried using it without boost. If I define ASIO_STANDALONE I still get a boost related error at type_traits.hpp on the line 46, because _WEBSOCKETPP_CPP11_TYPE_TRAITS_ is not defined. Should I define that one as well? BTW it would be nice to have some instructions for. The only thing I found regarding the topic is this thread and the FAQ, but those don't mention anything else apart from ASIO_STANDALONE. 

And also, I saw some warning during the compilation that I should not define ASIO_STANDALONE myself...

**Comment by ceztko** [comment]
@ArosPrince 
> Should I define that one as well? 

You probably have MSVC. C++11 detection is non functional in websocketpp using MSVC beause it relies on __cplusplus valorization which is something MSVC still doesn't do yet. Just give an hint by defining manually `_WEBSOCKETPP_CPP11_STRICT_` before including anything in websocketpp.
